### ISSUE TITLE
I cant find the content game ?

### ISSUE THREAD

**Issue by khotaonickvai** [rspforhp/PVZdotnet-ready-to-mod#1]
i readed and see "extract content game" but where the content game i can find??

**Comment by rspforhp** [comment]
its already there, this is ready to mod

**Comment by khotaonickvai** [comment]
> its already there, this is ready to mod

  can you give me a link ? i can not find xxx.xnb file

**Comment by rspforhp** [comment]
u should check out boxeds repo, its should be in his solution https://github.com/b-0-x-3-d/PVZ.NETMOD

**Comment by rspforhp** [comment]
Closed
