### ISSUE TITLE
WARNING: THIS REPO WAS SPLIT FROM ITS ORIGINAL MAINTAINERS

### ISSUE THREAD

**Issue by Mewnojs** [rspforhp/PVZdotnet-ready-to-mod#2]
This is an exact-copy of an old codebase of the repository of mine. Although the git history suggests it was "commited" in 2022, it is actually older, using an out-of-support .NET version, and **cannot even compile** without a bunch of tweaks.
Visit [here](https://github.com/Mewnojs/PlantsVsZombies.NET) for a repository with full version history, actively maintained (we need more participants!), ready to use, and with some quickstart guides.

**Comment by Mewnojs** [comment]
Btw I have to open this issue after encountering two users in a row asking for help (in the PvZ.NET Discord server) on compiling this repo. No offense.

**Comment by rspforhp** [comment]
It is just ur git but with assets inside that I made for Personal use, if people want a working one look for a working one

**Comment by rspforhp** [comment]
If u want a good one, I think b0xed made one with fixes and shit, not sure
